---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"
        ports:
        - containerPort: 9113
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;  
            deny all;         
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: 9113
