---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;  
            deny all;         
        }
    }