---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.0.2.15:30996/nginx-custom:latest@sha256:1ab62773be70324a7ffbf96752d5c4efedb4a2c0388cfba60aa401c442d0ae5f
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: nginx-exporter
        image: 10.0.2.15:30996/nginx-custom:latest@sha256:1ab62773be70324a7ffbf96752d5c4efedb4a2c0388cfba60aa401c442d0ae5f
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"
        ports:
        - containerPort: 9113
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config


