---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 10.0.2.15:30996/nginx-custom:latest@sha256:531d882ce7269af5d5fc1be8dd9b77c328b4240d90db891e00b540ec815b02a1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: nginx-exporter
        image: 10.0.2.15:30996/nginx-custom:latest@sha256:531d882ce7269af5d5fc1be8dd9b77c328b4240d90db891e00b540ec815b02a1
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:80/nginx_status"
        ports:
        - containerPort: 9113
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config


