resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:881fcf4bc7fd7a5ddd02958840c24822c9258f0fd78de58a92ddcb6697dd8771
  name: nginx
  newName: 10.0.2.15:30996/nginx-custom
