resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:992da09640c094c863f5c390bf529361c0034fc146ce08e109a7fd7ec8a7841a
  name: nginx
  newName: 10.0.2.15:30996/nginx-custom
