resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dd326220b00a792ed339896c21dc622cf308c7e9fc0ef8183e6ab8208a847b46
  name: 10.0.2.15:30996/nginx-custom
  newName: local-registry.registry.svc.cluster.local:5000/nginx-custom
- digest: sha256:33fdf7d2e4bd85ba56a3b43322901497b1faff3a842044ae253e5c331e18f781
  name: nginx
  newName: local-registry.registry.svc.cluster.local:5000/nginx-custom
