resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:9b545a92e8882bd53b2356d678c71d5bd062634a7f62213ebda866a181cc5a27
  name: nginx
  newName: 10.0.2.15:30996/nginx-custom
