resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:6221128d20e151b674b4bb4867b67618b02dfc74b203810e6d7573a7baf32e67
  name: nginx
  newName: 10.0.2.15:30996/nginx-custom
