---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
#  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: 9113